name: Keep Render Bot Alive

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  ping-job:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render App
        run: |
          curl -s https://deltabot-ndpv.onrender.com/ping
